-- Seed all 48 static events into Supabase
-- Run in SQL Editor at supabase.com

-- Clear existing static events first (keeps user-submitted ones)
DELETE FROM public.events WHERE source = 'static' OR source IS NULL;

INSERT INTO public.events (name, city, state, date, category, accepts_indie, stand_info, cost, audience, score, sort_order, url, notes, source) VALUES

-- JUL 2026
('Anime Friends 2026 — São Paulo','São Paulo','SP','2–5 Jul 2026','Geek/Pop',false,'Stand pago (área gamer)','A confirmar','80 000+',6,20260702,'https://www.animefriends.com.br','Maior evento de cultura pop e games do Brasil. Área gamer, cosplay, shows. Headliner: banda japonesa Hanabie. Já realizado.','static'),
('GGCON 2026 — Natal','Natal','RN','3–5 Jul 2026','Grande Feira',false,'Expositores (ver site oficial)','A confirmar','50 000 esperados',8,20260703,'https://www.ggcon.org','Maior evento de cultura geek/gamer do Rio Grande do Norte. Centro de Convenções de Natal. Banda Galneryus (Japão), dubladores Wendel Bezerra (Goku), Luiz Carlos Persy, Feh Dubs. Palco Games, K-pop, cosplay, eSports, Just Dance. Já realizado.','static'),
('TecnoGame Manaus — 5 Anos','Manaus','AM','10–12 Jul 2026','Grande Feira',false,'Feiras de expositores (ver organização)','A confirmar','150 000 esperados',7,20260710,'https://tecnogamebr.com.br','Centro de Convenções Vasco Vasques. 5 anos! Show da banda japonesa FLOW (1ª vez no Norte). Feira de expositores, lojas, cosplay. 150 mil esperados. Já realizado.','static'),
('SANA 2026 — Fortaleza','Fortaleza','CE','10–12 Jul 2026','Geek/Pop',false,'Stand pago','A confirmar','30 000+',6,20260710,'https://sana.com.br','Maior evento geek do Norte e Nordeste do Brasil. Games, cosplay, shows, cultura pop. Boa para devs da região. Já realizado.','static'),
('Dreamfest — Mega Festival Geek','Esteio','RS','11–12 Jul 2026','Geek/Pop',false,'Stand pago (ver organização)','A confirmar','10 000+',6,20260711,'https://www.instagram.com/dreamfestoficial','Parque da Expointer, Esteio (RS). O evento geek mais mágico do Sul do Brasil. Games, cosplay, cultura pop. Bom para devs gaúchos. Já realizado.','static'),
('Pequi Geek 2026 — 4ª edição','Goiânia','GO','12 Jul 2026','Geek/Pop',false,'Expositores (ver site)','R$20–40','3 000+',5,20260712,'https://gazetaculturismo.com.br/pequi-geek-2026-chega-a-4a-edicao','Shopping Estação Goiânia. Anime, games, cosplay, K-pop, entretenimento asiático. 4ª edição da Organização Nerd de Goiás. Já realizado.','static'),
('Goytacon 2026','Campos dos Goytacazes','RJ','18 Jul 2026','Geek/Pop',false,'Expositores (ver organização)','A confirmar','2 000+',5,20260718,'https://geekconnection.net/Calendario/782','Evento geek em Campos dos Goytacazes, interior do RJ. Cosplay, games, anime. Bom para devs da região Norte Fluminense. Já realizado.','static'),
('Animeuai 2026 — Minas Gerais','Interior MG','MG','18–19 Jul 2026','Geek/Pop',false,'Stand pago','A confirmar','1 000–3 000',5,20260718,'https://geekconnection.net/Calendario/752','Evento de anime e cultura geek em Minas Gerais (interior). Games, cosplay, K-pop. Já realizado.','static'),
('Retro Game Hall — RJ Tijuca','Rio de Janeiro','RJ','19 Jul 2026','Retro',true,'Arena Indie Retro + artist alley','Ingresso simbólico','500–1 500',6,20260719,'https://www.sympla.com.br/evento/retro-game-hall/3293000','Tijuca Tênis Club, RJ. Arena Retro Games, Arena Fliperama, Pump It Up, Arena Indie Retro (jogos novos com alma nostálgica), artist alley pixel art, concurso cosplay, feira de games. Já realizado.','static'),
('RetroCon 2026 — São Paulo','São Paulo','SP','24–26 Jul 2026','Retro',true,'Estúdios indie podem expor (área exposição)','Ver site','10 000+',7,20260724,'https://retrocon.com.br','12 000m² Expo Center Transamérica. Arcades originais, influenciadores (BRKsEdu, Rato Borrachudo), estúdios indie, locadoras temáticas. Organizado por Casa do Videogame + WarpZone + Mr. Games. Já realizado.','static'),
('Super-Con Recife 2026','Recife','PE','24–26 Jul 2026','Geek/Pop',false,'Stand pago','A confirmar','20 000+',6,20260724,'https://conecta.recife.pe.gov.br/evento/4832','Principal evento geek do Nordeste. Centro de Convenções de Pernambuco. Cosplay, games, anime, quadrinhos. Já realizado.','static'),
('Exodus Experience 2026 — São José SC','São José','SC','25–26 Jul 2026','Geek/Pop',false,'Expositores (ver organização)','R$35+','3 000+',5,20260725,'https://www.ndgames.com.br/noticias/exodus-experience-2026-sao-jose-sc','São José, SC. Anime, games, cosplay, K-pop, board games, technology. 2 dias, programação 11h–21h. Novo evento catarinense. Já realizado.','static'),
('Taquara Geek 2026','Taquara','RJ','25–26 Jul 2026','Geek/Pop',false,'Expositores (ver organização)','A confirmar','500–1 500',5,20260725,'https://geekconnection.net/Calendario/784','Evento geek em Taquara, RJ. Anime, cosplay, games. Pequeno mas com comunidade local engajada. Já realizado.','static'),

-- AGO 2026
('SpiderCon 2026 — Rio de Janeiro','Rio de Janeiro','RJ','2 Ago 2026','Geek/Pop',false,'Expositores (ver organização)','A confirmar','1 000–3 000',5,20260802,'https://geekconnection.net/Calendario/723','Centro do Rio de Janeiro. Evento geek, cosplay, games. Comunidade ativa da Lucena Corp no RJ.','static'),
('Jornada Nerd 2026 — São José SC','São José','SC','15 Ago 2026','Geek/Pop',false,'Expositores (ver organização)','A confirmar','1 000+',5,20260815,'https://geekconnection.net/Calendario/742','São José, SC. Evento geek com anime, games, cosplay. Bom para devs de SC que querem presença regional.','static'),
('Video Game Hall — RJ','Rio de Janeiro','RJ','16 Ago 2026','Retro',true,'Arena com área indie','Ingresso simbólico','500–1 000',6,20260816,'https://geekconnection.net/Calendario/724','Centro do Rio. Evento de games retro e indie com arena de jogatina. Produção Lucena Corp. Boa para devs cariocas exibirem projetos.','static'),
('Pichau Arena 2026 — Joinville','Joinville','SC','Ago/Set 2026','Grande Feira',false,'Stand pago (ver organização)','A confirmar','20 000+',7,20260820,'https://evento.pichauarena.com.br','Maior evento gamer do Sul do Brasil, organizado pela Pichau (maior loja gamer da América Latina). 200+ PCs, simuladores de drift, eSports, cosplay, K-pop. Joinville SC. Data exata a confirmar.','static'),

-- SET 2026
('GO Game Festival 2026','Goiânia','GO','11–13 Set 2026','Grande Feira',false,'Stand pago + área de networking','A confirmar','10 000+',7,20260911,'https://www.sympla.com.br/evento/go-game-festival-2026/3479261','Passeio das Águas Shopping, Goiânia. 3ª edição, 8 000m², R$50 000 em premiações. Valorant, LoL, CS2, Tekken, SF6, MK1. 30+ horas de programação. Maior evento geek de Goiás.','static'),
('Tijuca Geek Festival — Set/RJ','Rio de Janeiro','RJ','13 Set 2026','Geek/Pop',false,'Expositores (ver organização)','A confirmar','1 000–3 000',5,20260913,'https://tijucageekfestival.com.br','Tijuca Tênis Club, RJ. Anime, cosplay, games, K-pop, card games. Edição de setembro da série de eventos da Lucena Corp no bairro Otaku do Rio.','static'),
('Bangu Geek — Set/RJ','Rio de Janeiro','RJ','13 Set 2026','Geek/Pop',false,'Expositores (ver organização)','A confirmar','500–2 000',5,20260913,'https://geekconnection.net/Calendarios/RJ','Bangu, Rio de Janeiro. Evento geek da comunidade carioca para a Zona Oeste do Rio.','static'),
('Geek Retro Centro — Set/RJ','Rio de Janeiro','RJ','20 Set 2026','Retro',false,'Expositores (ver organização)','A confirmar','500–1 500',5,20260920,'https://geekconnection.net/Calendarios/RJ','Centro do Rio de Janeiro. Evento retrogaming na região central. Consoles, fliperamas, comunidade retro carioca.','static'),

-- OUT 2026
('Brasil Game Show 2026 — BGS','São Paulo','SP','9–12 Out 2026','Grande Feira',true,'BGS Indie (stand pago — seleção)','Contactar site oficial','300 000+',10,20261009,'https://brasilgameshow.com.br','17ª edição. Maior feira de games das Américas. 306 798 visitantes em 2025. 67 jogos independentes na BGS Indie. Dia 9 exclusivo para imprensa e B2B. O evento mais importante do Brasil para um dev indie.','static'),
('Guapimirim Anime Fest — RJ','Guapimirim','RJ','11 Out 2026','Geek/Pop',false,'Expositores','A confirmar','500–1 000',4,20261011,'https://geekconnection.net/Calendarios/RJ','Guapimirim, interior do Rio de Janeiro. Evento de anime e cultura geek para comunidade local.','static'),
('Geek Prime 2026 — Goiânia','Goiânia','GO','Out 2026','Geek/Pop',false,'Expositores (ver 4.events)','A confirmar','3 000+',5,20261015,'https://lets.4.events/geek-prime-2026-goiania-C25009E7','Evento geek de Goiânia. Cosplay, games, anime. Data exata a confirmar — acompanhar site oficial.','static'),
('Video Game Hall — Out/RJ','Rio de Janeiro','RJ','25 Out 2026','Retro',true,'Arena com espaço indie','Ingresso simbólico','500–1 500',6,20261025,'https://geekconnection.net/Calendarios/RJ','Tijuca, Rio de Janeiro. Edição de outubro do Video Game Hall — games clássicos e indie. Boa oportunidade para devs cariocas com projetos em desenvolvimento.','static'),

-- NOV 2026
('RetroSC 2026 — 2ª edição','Florianópolis','SC','7 Nov 2026','Retro',true,'Espaço para devs indie (ver site)','Acessível','500–1 000',6,20261107,'https://retrosc.org','Sesc Cacupé, Florianópolis. Aceita desenvolvedores indie — espaço para mostrar projetos. Caráter filantrópico. Comunidade de 400+ membros em SC.','static'),
('Pechincha Geek — Nov/RJ','Rio de Janeiro','RJ','8 Nov 2026','Geek/Pop',false,'Expositores','A confirmar','500–1 500',5,20261108,'https://geekconnection.net/Calendarios/RJ','Pechincha, zona oeste do Rio. Evento geek da comunidade local.','static'),
('REC''n''Play 2026 — Recife','Recife','PE','11–14 Nov 2026','Networking/B2B',false,'Stand (startups/inovação)','A confirmar','20 000+',7,20261111,'https://recnplay.pe.gov.br','O "Carnaval do Conhecimento de Recife". Maior festival de tecnologia e economia criativa do Nordeste. Secção de games e economia criativa. Ótimo para devs conectarem com investidores.','static'),
('Tijuca Geek — Nov/RJ','Rio de Janeiro','RJ','15 Nov 2026','Geek/Pop',false,'Expositores (ver organização)','A confirmar','1 000–3 000',5,20261115,'https://tijucageekfestival.com.br','Edição de novembro do Tijuca Geek Festival. Tijuca Tênis Club, RJ. Games, cosplay, anime, K-pop.','static'),
('Canal 3 Expo 2026 — São Paulo','São Paulo','SP','20–22 Nov 2026','Retro',true,'Expositor/lojista (ver site)','A confirmar','5 000–15 000',7,20261120,'https://canal3expo.com.br','Maior encontro retrogamer da América Latina desde 1999. Consoles originais, exposições imersivas, CTWC (campeonato mundial de Tetris). Devs com estética retrô podem expor.','static'),
('Bom Jesus Itabapoana — Comics Fest RJ','Bom Jesus do Itabapoana','RJ','21 Nov 2026','Geek/Pop',false,'Expositores','A confirmar','500–1 000',4,20261121,'https://geekconnection.net/Calendarios/RJ','Bom Jesus do Itabapoana, interior do RJ. Comics fest com quadrinhos, games e cultura pop. Evento pequeno regional.','static'),
('Super-Con Recife — 2ª Edição 2026','Recife','PE','Nov 2026','Geek/Pop',false,'Stand pago','A confirmar','10 000+',6,20261130,'https://superconvencao.com.br','Segunda edição anual da Super-Con em Recife. Principal evento geek de Pernambuco. Data exata a confirmar — acompanhar redes sociais.','static'),

-- DEZ 2026
('CCXP 2026 — São Paulo','São Paulo','SP','3–6 Dez 2026','Geek/Pop',false,'Stand pago (ver organização)','A confirmar','300 000+',8,20261203,'https://ccxp.com.br','Maior festival de cultura pop do mundo. São Paulo Expo. Área de games com demos, competições e experiências interativas. Público enorme e diverso. Ótimo para visibilidade com mídia.','static'),
('Geek Tijuca Dez — Festival Final','Rio de Janeiro','RJ','5–6 Dez 2026','Geek/Pop',false,'Expositores (ver organização)','A confirmar','1 000–3 000',5,20261205,'https://geekconnection.net/Calendarios/RJ','Tijuca, RJ. Edição de dezembro, encerrando o ciclo anual de eventos geek da Lucena Corp na Tijuca.','static'),
('Video Game Hall Centro — Dez/RJ','Rio de Janeiro','RJ','5–6 Dez 2026','Retro',true,'Arena indie + expositores','Ingresso simbólico','500–1 500',5,20261205,'https://retrogamehall.com.br','Edição de encerramento de dezembro no Tijuca TTC, RJ. Série Lucena Corp — games clássicos, indie, cosplay.','static'),
('Pechincha Geek Dez — Festival Natal RJ','Rio de Janeiro','RJ','Dez 2026','Geek/Pop',false,'Expositores','A confirmar','500–1 500',4,20261215,'https://geekconnection.net/Calendarios/RJ','Pechincha, zona oeste do Rio de Janeiro. Edição de encerramento de ano da série de eventos geek da região.','static'),

-- DATA A CONFIRMAR (2026)
('Invasão Geek 2026 — Natal SESC','Natal','RN','2026 (data a confirmar)','Geek/Pop',false,'Área gaming (ver SESC RN)','Gratuito (SESC)','1 000–3 000',6,20261299,'https://sescrn.com.br','SESC Natal. Campeonatos de jogos online e atividades geek. Entrada gratuita para beneficiários SESC. Acompanhar agenda do SESC RN.','static'),
('Game-Con Bahia 2026','Salvador','BA','2026 (data a confirmar)','Geek/Pop',false,'Stand pago (ver organização)','A confirmar','5 000+',6,20261299,'https://calendarionerd.com.br/evento/gamecon-bahia-2026','Grande evento de games e cultura geek da Bahia. Salvador. Data exata a confirmar no site do CalendárioNerd.','static'),
('Nova Friburgo Geek Fest — RJ','Nova Friburgo','RJ','2026 (data a confirmar)','Geek/Pop',false,'Arena Gamer + expositores','A confirmar','1 000–3 000',5,20261299,'https://geekconnection.net','Nova Friburgo, serra fluminense RJ. Cultura pop, games, cosplay, K-pop. Dublador Pedro Azevedo confirmado. Arena Gamer com consoles free play. Data exata a confirmar.','static'),
('Economia Criativa Fluminense — Indie Games','Rio de Janeiro','RJ','2026 (data a confirmar)','Indie',true,'Stand gratuito para indie','Gratuito para selecionados','1 000–3 000',7,20261299,'https://geekconnection.net','Evento de economia criativa fluminense com foco em jogos: demos e lançamentos de jogos indie eletrônicos, jogos analógicos, board games, RPG, artist alley. Espaço gratuito para devs indie. Data a confirmar.','static'),

-- RECORRENTES
('Estúdio Riachuelo — Gameplays Indie','Curitiba','PR','Recorrente','Indie',true,'Participação gratuita','Gratuito','50–200',6,99000000,'https://indiebrasilis.com.br','Espaço em Curitiba com gameplays regulares de jogos indie brasileiros. Feedback e networking local no Paraná.','static'),
('Encontro Mulheres nos Jogos — HUB Goiás','Goiânia','GO','Recorrente','Networking/B2B',true,'Participação gratuita','Gratuito','100–300',6,99000001,'https://indiebrasilis.com.br','7ª edição do Encontro de Mulheres nos Jogos no HUB Goiás. Networking e visibilidade para devs mulheres. Pequeno mas muito relevante para a comunidade indie nacional.','static'),
('Maricá Games — RJ','Maricá','RJ','Recorrente anual','Geek/Pop',true,'Área Arena Games (devs locais)','Gratuito','5 000–20 000',6,99000002,'https://retrogamehall.com.br','Maricá, Rio de Janeiro. Evento gamer regional apoiado pela prefeitura. Inclui Museu dos Games e espaço para devs locais. Boa para devs da Região dos Lagos.','static'),

-- 2027
('GGJ Porto Alegre 2027','Porto Alegre','RS','Jan/Fev 2027','Indie',true,'Jam aberta (gratuita)','Gratuito','100–200 devs',7,20270115,'https://globalgamejam.org','Sede da Global Game Jam em Porto Alegre. Networking com devs gaúchos, prototipagem de jogos em 48h. Comunidade ativa no RS.','static'),
('GGJ São Paulo USP / PUC / SENAI 2027','São Paulo','SP','Jan/Fev 2027','Indie',true,'Jam aberta (gratuita ou taxa simbólica)','Gratuito','200–500 devs por sede',8,20270115,'https://globalgamejam.org','Várias sedes na capital: USP, PUC-SP, SENAI, FIAP e outras. São Paulo concentra o maior número de sedes da GGJ no Brasil. Gratuito ou com taxa simbólica para brindes.','static'),
('GGJ Brasil 2027 — Várias sedes','São Paulo, RJ, Porto Alegre, Recife...','Nac','Jan/Fev 2027','Indie',true,'Jam aberta (gratuita)','Gratuito','50–600 devs por sede',8,20270115,'https://globalgamejam.org','Sedes por todo o Brasil: Curitiba PUCPR (600 devs, maior do mundo), SP, RJ, Porto Alegre, Recife, Manaus, Fortaleza e outros. Gratuito na maioria das sedes. Ótimo para networking e protótipos.','static'),
('Brasília Game Festival 2027','Brasília','DF','Mai 2027','Indie',true,'Mostra Indie (ABRING, seleção gratuita)','Gratuito para selecionados','20 000+',9,20270501,'https://brasiliagamefestival.com.br','Próxima edição anual. Mostra Indie com dezenas de estúdios. Campeonato de Playtest. Entrada gratuita para o público. Acompanhar site para inscrições.','static'),
('Indie Brazil Showcase 2027 (+ edições intermédias)','Online','Nac','2027 (+ 2 edições intermédias)','Online',true,'Candidatura gratuita','Gratuito','100 000+ views',9,20270601,'https://gamewire.com.br/indie-brazil-showcase','Próxima edição principal + 2 edições intermédias. A 1ª edição reuniu 59 estúdios e 87 jogos. Showcase 100% indie BR ao estilo Nintendo Direct. Inscrições abertas no site.','static');
